/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef chord_TYPES_H
#define chord_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class SystemException;

class RFileMetadata;

class RFile;

class NodeID;

typedef struct _SystemException__isset {
  _SystemException__isset() : message(false) {}
  bool message :1;
} _SystemException__isset;

class SystemException : public ::apache::thrift::TException {
 public:

  SystemException(const SystemException&);
  SystemException& operator=(const SystemException&);
  SystemException() : message() {
  }

  virtual ~SystemException() throw();
  std::string message;

  _SystemException__isset __isset;

  void __set_message(const std::string& val);

  bool operator == (const SystemException & rhs) const
  {
    if (__isset.message != rhs.__isset.message)
      return false;
    else if (__isset.message && !(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const SystemException &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SystemException & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
  mutable std::string thriftTExceptionMessageHolder_;
  const char* what() const throw();
};

void swap(SystemException &a, SystemException &b);

inline std::ostream& operator<<(std::ostream& out, const SystemException& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _RFileMetadata__isset {
  _RFileMetadata__isset() : filename(false), version(false), contentHash(false) {}
  bool filename :1;
  bool version :1;
  bool contentHash :1;
} _RFileMetadata__isset;

class RFileMetadata : public virtual ::apache::thrift::TBase {
 public:

  RFileMetadata(const RFileMetadata&);
  RFileMetadata& operator=(const RFileMetadata&);
  RFileMetadata() : filename(), version(0), contentHash() {
  }

  virtual ~RFileMetadata() throw();
  std::string filename;
  int32_t version;
  std::string contentHash;

  _RFileMetadata__isset __isset;

  void __set_filename(const std::string& val);

  void __set_version(const int32_t val);

  void __set_contentHash(const std::string& val);

  bool operator == (const RFileMetadata & rhs) const
  {
    if (__isset.filename != rhs.__isset.filename)
      return false;
    else if (__isset.filename && !(filename == rhs.filename))
      return false;
    if (__isset.version != rhs.__isset.version)
      return false;
    else if (__isset.version && !(version == rhs.version))
      return false;
    if (__isset.contentHash != rhs.__isset.contentHash)
      return false;
    else if (__isset.contentHash && !(contentHash == rhs.contentHash))
      return false;
    return true;
  }
  bool operator != (const RFileMetadata &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RFileMetadata & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(RFileMetadata &a, RFileMetadata &b);

inline std::ostream& operator<<(std::ostream& out, const RFileMetadata& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _RFile__isset {
  _RFile__isset() : meta(false), content(false) {}
  bool meta :1;
  bool content :1;
} _RFile__isset;

class RFile : public virtual ::apache::thrift::TBase {
 public:

  RFile(const RFile&);
  RFile& operator=(const RFile&);
  RFile() : content() {
  }

  virtual ~RFile() throw();
  RFileMetadata meta;
  std::string content;

  _RFile__isset __isset;

  void __set_meta(const RFileMetadata& val);

  void __set_content(const std::string& val);

  bool operator == (const RFile & rhs) const
  {
    if (__isset.meta != rhs.__isset.meta)
      return false;
    else if (__isset.meta && !(meta == rhs.meta))
      return false;
    if (__isset.content != rhs.__isset.content)
      return false;
    else if (__isset.content && !(content == rhs.content))
      return false;
    return true;
  }
  bool operator != (const RFile &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RFile & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(RFile &a, RFile &b);

inline std::ostream& operator<<(std::ostream& out, const RFile& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _NodeID__isset {
  _NodeID__isset() : id(false), ip(false), port(false) {}
  bool id :1;
  bool ip :1;
  bool port :1;
} _NodeID__isset;

class NodeID : public virtual ::apache::thrift::TBase {
 public:

  NodeID(const NodeID&);
  NodeID& operator=(const NodeID&);
  NodeID() : id(), ip(), port(0) {
  }

  virtual ~NodeID() throw();
  std::string id;
  std::string ip;
  int32_t port;

  _NodeID__isset __isset;

  void __set_id(const std::string& val);

  void __set_ip(const std::string& val);

  void __set_port(const int32_t val);

  bool operator == (const NodeID & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(ip == rhs.ip))
      return false;
    if (!(port == rhs.port))
      return false;
    return true;
  }
  bool operator != (const NodeID &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NodeID & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(NodeID &a, NodeID &b);

inline std::ostream& operator<<(std::ostream& out, const NodeID& obj)
{
  obj.printTo(out);
  return out;
}



#endif
