/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef chord_CONSTANTS_H
#define chord_CONSTANTS_H

#include "chord_types.h"



class chordConstants {
 public:
  chordConstants();

};

extern const chordConstants g_chord_constants;



#endif
